In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name": ["rohan" , "krish" , "alash"] ,
    "marks" : [84, 73 , 12] , 
    "city" : ['ggn' , 'delhi' , 'indore']
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

    name  marks    city
0  rohan     84     ggn
1  krish     73   delhi
2  alash     12  indore

In [5]:
df.to_csv('marks.csv')

In [6]:
df.to_csv('marks.csv' , index = False)

In [7]:
df.head(2)

    name  marks   city
0  rohan     84    ggn
1  krish     73  delhi

In [8]:
df.tail(2)

    name  marks    city
1  krish     73   delhi
2  alash     12  indore

In [9]:
df.describe()

           marks
count   3.000000
mean   56.333333
std    38.785736
min    12.000000
25%    42.500000
50%    73.000000
75%    78.500000
max    84.000000

In [10]:
krish = pd.read_csv('random.csv')

In [11]:
krish

   train no  speed    city
0      1234    435     ggn
1      3435    546   delhi
2     23425    354  indore

In [12]:
krish['speed']

0    435
1    546
2    354
Name: speed, dtype: int64

In [13]:
krish['city'][2]

'indore'

In [14]:
krish['city'][2] = 'indore'

C:\Users\chaud\AppData\Local\Temp\ipykernel_17728\754150968.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  krish['city'][2] = 'indore'

In [15]:
krish

   train no  speed    city
0      1234    435     ggn
1      3435    546   delhi
2     23425    354  indore

In [16]:
krish.index=['first' , 'second' , 'third']

In [17]:
krish

        train no  speed    city
first       1234    435     ggn
second      3435    546   delhi
third      23425    354  indore

In [18]:
ser = pd.Series(np.random.rand(10))

In [19]:
ser

0    0.700211
1    0.992941
2    0.615103
3    0.201774
4    0.562091
5    0.420378
6    0.930084
7    0.641068
8    0.522085
9    0.989977
dtype: float64

In [20]:
newdf = pd.DataFrame(np.random.rand(334,5) , index = np.arange(334))

In [21]:
newdf

            0         1         2         3         4
0    0.725022  0.955012  0.365011  0.776109  0.279673
1    0.912002  0.421795  0.512429  0.633258  0.007564
2    0.959900  0.322290  0.089730  0.844433  0.904390
3    0.588272  0.922632  0.767899  0.515659  0.074170
4    0.523455  0.619775  0.492090  0.864499  0.932525
..        ...       ...       ...       ...       ...
329  0.864147  0.870512  0.299589  0.848446  0.772379
330  0.208099  0.210990  0.777263  0.204774  0.272951
331  0.473057  0.333650  0.616777  0.167659  0.578994
332  0.890463  0.039692  0.429368  0.130846  0.445001
333  0.192699  0.685667  0.466893  0.395842  0.384943

[334 rows x 5 columns]

In [22]:
type(newdf)

pandas.DataFrame

In [23]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.511006    0.512991    0.507117    0.492170    0.479767
std      0.294803    0.291908    0.281565    0.283248    0.278273
min      0.003700    0.011665    0.007823    0.005403    0.000050
25%      0.242910    0.259513    0.263231    0.235993    0.266095
50%      0.521255    0.545360    0.494551    0.506172    0.472505
75%      0.758285    0.765153    0.754742    0.740763    0.725971
max      0.993648    0.992826    0.998592    0.998445    0.989766

In [24]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [25]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [26]:
newdf.to_numpy()

array([[0.72502172, 0.95501178, 0.36501094, 0.77610908, 0.2796725 ],
       [0.91200155, 0.4217947 , 0.5124292 , 0.63325765, 0.00756385],
       [0.95989974, 0.32228982, 0.08973033, 0.84443266, 0.90438995],
       ...,
       [0.47305726, 0.33364953, 0.61677734, 0.16765867, 0.57899383],
       [0.89046273, 0.0396923 , 0.42936792, 0.13084564, 0.44500134],
       [0.19269942, 0.68566741, 0.4668931 , 0.39584243, 0.38494251]],
      shape=(334, 5))

In [27]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.725022,0.912002,0.959900,0.588272,0.523455,0.437063,0.518136,0.053638,0.127065,0.789138,...,0.776233,0.867579,0.657484,0.626532,0.077815,0.864147,0.208099,0.473057,0.890463,0.192699
1,0.955012,0.421795,0.322290,0.922632,0.619775,0.589753,0.587550,0.285925,0.750148,0.195349,...,0.700075,0.979879,0.656647,0.256970,0.351111,0.870512,0.210990,0.333650,0.039692,0.685667
2,0.365011,0.512429,0.089730,0.767899,0.492090,0.890101,0.115103,0.836804,0.834507,0.646079,...,0.070509,0.808543,0.892266,0.095022,0.649451,0.299589,0.777263,0.616777,0.429368,0.466893
3,0.776109,0.633258,0.844433,0.515659,0.864499,0.990636,0.869699,0.566881,0.983383,0.282875,...,0.519786,0.884119,0.163272,0.059520,0.148044,0.848446,0.204774,0.167659,0.130846,0.395842
4,0.279673,0.007564,0.904390,0.074170,0.932525,0.344843,0.105464,0.745595,0.474547,0.463238,...,0.303522,0.399408,0.120547,0.422061,0.762622,0.772379,0.272951,0.578994,0.445001,0.384943

In [28]:
newdf.head()

          0         1         2         3         4
0  0.725022  0.955012  0.365011  0.776109  0.279673
1  0.912002  0.421795  0.512429  0.633258  0.007564
2  0.959900  0.322290  0.089730  0.844433  0.904390
3  0.588272  0.922632  0.767899  0.515659  0.074170
4  0.523455  0.619775  0.492090  0.864499  0.932525

In [29]:
newdf.sort_index(axis = 0 , ascending = False)

            0         1         2         3         4
333  0.192699  0.685667  0.466893  0.395842  0.384943
332  0.890463  0.039692  0.429368  0.130846  0.445001
331  0.473057  0.333650  0.616777  0.167659  0.578994
330  0.208099  0.210990  0.777263  0.204774  0.272951
329  0.864147  0.870512  0.299589  0.848446  0.772379
..        ...       ...       ...       ...       ...
4    0.523455  0.619775  0.492090  0.864499  0.932525
3    0.588272  0.922632  0.767899  0.515659  0.074170
2    0.959900  0.322290  0.089730  0.844433  0.904390
1    0.912002  0.421795  0.512429  0.633258  0.007564
0    0.725022  0.955012  0.365011  0.776109  0.279673

[334 rows x 5 columns]

In [30]:
newdf.head()

          0         1         2         3         4
0  0.725022  0.955012  0.365011  0.776109  0.279673
1  0.912002  0.421795  0.512429  0.633258  0.007564
2  0.959900  0.322290  0.089730  0.844433  0.904390
3  0.588272  0.922632  0.767899  0.515659  0.074170
4  0.523455  0.619775  0.492090  0.864499  0.932525

In [31]:
newdf[0]

0      0.725022
1      0.912002
2      0.959900
3      0.588272
4      0.523455
         ...
329    0.864147
330    0.208099
331    0.473057
332    0.890463
333    0.192699
Name: 0, Length: 334, dtype: float64

In [32]:
newdf2 = newdf

In [33]:
newdf2

            0         1         2         3         4
0    0.725022  0.955012  0.365011  0.776109  0.279673
1    0.912002  0.421795  0.512429  0.633258  0.007564
2    0.959900  0.322290  0.089730  0.844433  0.904390
3    0.588272  0.922632  0.767899  0.515659  0.074170
4    0.523455  0.619775  0.492090  0.864499  0.932525
..        ...       ...       ...       ...       ...
329  0.864147  0.870512  0.299589  0.848446  0.772379
330  0.208099  0.210990  0.777263  0.204774  0.272951
331  0.473057  0.333650  0.616777  0.167659  0.578994
332  0.890463  0.039692  0.429368  0.130846  0.445001
333  0.192699  0.685667  0.466893  0.395842  0.384943

[334 rows x 5 columns]

In [34]:
newdf3 = newdf.copy()

In [35]:
newdf3

            0         1         2         3         4
0    0.725022  0.955012  0.365011  0.776109  0.279673
1    0.912002  0.421795  0.512429  0.633258  0.007564
2    0.959900  0.322290  0.089730  0.844433  0.904390
3    0.588272  0.922632  0.767899  0.515659  0.074170
4    0.523455  0.619775  0.492090  0.864499  0.932525
..        ...       ...       ...       ...       ...
329  0.864147  0.870512  0.299589  0.848446  0.772379
330  0.208099  0.210990  0.777263  0.204774  0.272951
331  0.473057  0.333650  0.616777  0.167659  0.578994
332  0.890463  0.039692  0.429368  0.130846  0.445001
333  0.192699  0.685667  0.466893  0.395842  0.384943

[334 rows x 5 columns]

In [36]:
newdf.loc[0,0] = 6554

In [37]:
newdf.head()

             0         1         2         3         4
0  6554.000000  0.955012  0.365011  0.776109  0.279673
1     0.912002  0.421795  0.512429  0.633258  0.007564
2     0.959900  0.322290  0.089730  0.844433  0.904390
3     0.588272  0.922632  0.767899  0.515659  0.074170
4     0.523455  0.619775  0.492090  0.864499  0.932525

In [38]:
newdf.columns = list('ABCDE')

In [39]:
newdf

               A         B         C         D         E
0    6554.000000  0.955012  0.365011  0.776109  0.279673
1       0.912002  0.421795  0.512429  0.633258  0.007564
2       0.959900  0.322290  0.089730  0.844433  0.904390
3       0.588272  0.922632  0.767899  0.515659  0.074170
4       0.523455  0.619775  0.492090  0.864499  0.932525
..           ...       ...       ...       ...       ...
329     0.864147  0.870512  0.299589  0.848446  0.772379
330     0.208099  0.210990  0.777263  0.204774  0.272951
331     0.473057  0.333650  0.616777  0.167659  0.578994
332     0.890463  0.039692  0.429368  0.130846  0.445001
333     0.192699  0.685667  0.466893  0.395842  0.384943

[334 rows x 5 columns]

In [40]:
newdf.head()

             A         B         C         D         E
0  6554.000000  0.955012  0.365011  0.776109  0.279673
1     0.912002  0.421795  0.512429  0.633258  0.007564
2     0.959900  0.322290  0.089730  0.844433  0.904390
3     0.588272  0.922632  0.767899  0.515659  0.074170
4     0.523455  0.619775  0.492090  0.864499  0.932525

In [41]:
newdf.loc[[1,2] , ['C','D']]

          C         D
1  0.512429  0.633258
2  0.089730  0.844433

In [42]:
newdf.loc[[1,2] ,:]

          A         B         C         D         E
1  0.912002  0.421795  0.512429  0.633258  0.007564
2  0.959900  0.322290  0.089730  0.844433  0.904390

In [43]:
newdf.loc[(newdf['A']<0.3) & (newdf['C']>0.3)]

            A         B         C         D         E
7    0.053638  0.285925  0.836804  0.566881  0.745595
8    0.127065  0.750148  0.834507  0.983383  0.474547
13   0.274655  0.924294  0.508348  0.062765  0.214132
14   0.263143  0.963555  0.364476  0.580659  0.387282
24   0.148945  0.040017  0.594973  0.896803  0.535564
..        ...       ...       ...       ...       ...
314  0.236127  0.778747  0.379580  0.419344  0.521060
320  0.166219  0.090387  0.327229  0.757796  0.562423
328  0.077815  0.351111  0.649451  0.148044  0.762622
330  0.208099  0.210990  0.777263  0.204774  0.272951
333  0.192699  0.685667  0.466893  0.395842  0.384943

[77 rows x 5 columns]

In [44]:
newdf.iloc[0,3]

np.float64(0.776109078003142)

In [45]:
newdf.head()

             A         B         C         D         E
0  6554.000000  0.955012  0.365011  0.776109  0.279673
1     0.912002  0.421795  0.512429  0.633258  0.007564
2     0.959900  0.322290  0.089730  0.844433  0.904390
3     0.588272  0.922632  0.767899  0.515659  0.074170
4     0.523455  0.619775  0.492090  0.864499  0.932525

In [46]:
newdf.drop(1)

               A         B         C         D         E
0    6554.000000  0.955012  0.365011  0.776109  0.279673
2       0.959900  0.322290  0.089730  0.844433  0.904390
3       0.588272  0.922632  0.767899  0.515659  0.074170
4       0.523455  0.619775  0.492090  0.864499  0.932525
5       0.437063  0.589753  0.890101  0.990636  0.344843
..           ...       ...       ...       ...       ...
329     0.864147  0.870512  0.299589  0.848446  0.772379
330     0.208099  0.210990  0.777263  0.204774  0.272951
331     0.473057  0.333650  0.616777  0.167659  0.578994
332     0.890463  0.039692  0.429368  0.130846  0.445001
333     0.192699  0.685667  0.466893  0.395842  0.384943

[333 rows x 5 columns]

In [47]:
newdf.drop(['B'],axis=1 , inplace = True)

In [48]:
newdf

               A         C         D         E
0    6554.000000  0.365011  0.776109  0.279673
1       0.912002  0.512429  0.633258  0.007564
2       0.959900  0.089730  0.844433  0.904390
3       0.588272  0.767899  0.515659  0.074170
4       0.523455  0.492090  0.864499  0.932525
..           ...       ...       ...       ...
329     0.864147  0.299589  0.848446  0.772379
330     0.208099  0.777263  0.204774  0.272951
331     0.473057  0.616777  0.167659  0.578994
332     0.890463  0.429368  0.130846  0.445001
333     0.192699  0.466893  0.395842  0.384943

[334 rows x 4 columns]

In [49]:
newdf.reset_index(drop = True , inplace = True)

In [50]:
newdf

               A         C         D         E
0    6554.000000  0.365011  0.776109  0.279673
1       0.912002  0.512429  0.633258  0.007564
2       0.959900  0.089730  0.844433  0.904390
3       0.588272  0.767899  0.515659  0.074170
4       0.523455  0.492090  0.864499  0.932525
..           ...       ...       ...       ...
329     0.864147  0.299589  0.848446  0.772379
330     0.208099  0.777263  0.204774  0.272951
331     0.473057  0.616777  0.167659  0.578994
332     0.890463  0.429368  0.130846  0.445001
333     0.192699  0.466893  0.395842  0.384943

[334 rows x 4 columns]

In [51]:
newdf.loc[:,['B']] = None

In [52]:
newdf

               A         C         D         E     B
0    6554.000000  0.365011  0.776109  0.279673  None
1       0.912002  0.512429  0.633258  0.007564  None
2       0.959900  0.089730  0.844433  0.904390  None
3       0.588272  0.767899  0.515659  0.074170  None
4       0.523455  0.492090  0.864499  0.932525  None
..           ...       ...       ...       ...   ...
329     0.864147  0.299589  0.848446  0.772379  None
330     0.208099  0.777263  0.204774  0.272951  None
331     0.473057  0.616777  0.167659  0.578994  None
332     0.890463  0.429368  0.130846  0.445001  None
333     0.192699  0.466893  0.395842  0.384943  None

[334 rows x 5 columns]

In [53]:
newdf['B'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
329    True
330    True
331    True
332    True
333    True
Name: B, Length: 334, dtype: bool

In [54]:
df.shape

(3, 3)

In [55]:
newdf.shape

(334, 5)

In [56]:
df.info

<bound method DataFrame.info of     name  marks    city
0  rohan     84     ggn
1  krish     73   delhi
2  alash     12  indore>

In [57]:
df['name'].value_counts(dropna=False)

name
rohan    1
krish    1
alash    1
Name: count, dtype: int64

In [59]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [62]:
data = pd.read_excel('random.xlsx')

In [63]:
data

   train no  speed    city
0      1234    435     ggn
1      3435    546   delhi
2     23425    354  indore